# Generated by Django 6.0.4 on 2026-04-21 09:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_employee_allowance_airtime_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATED', 'Generated'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('channel', models.CharField(blank=True, choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('BOTH', 'Both'), ('MANUAL_DOWNLOAD', 'Manual Download')], max_length=16)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='landlord_statements/%Y/%m/')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_notes', models.CharField(blank=True, max_length=255)),
                ('total_cost', models.BigIntegerField(default=0)),
                ('total_paid', models.BigIntegerField(default=0)),
                ('total_balance', models.BigIntegerField(default=0)),
                ('commission_amount', models.BigIntegerField(default=0)),
                ('landlord_net', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='core.landlord')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landlord_statements_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end', '-id'],
                'indexes': [models.Index(fields=['landlord', '-period_end'], name='portal_land_landlor_f7203d_idx'), models.Index(fields=['status'], name='portal_land_status_223582_idx')],
                'constraints': [models.UniqueConstraint(fields=('landlord', 'period_start', 'period_end'), name='landlord_statement_unique_period')],
            },
        ),
    ]
