# Generated by Django 6.0.4 on 2026-04-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhoccharge',
            name='utility_kind',
            field=models.CharField(blank=True, choices=[('WATER', 'Water'), ('GARBAGE', 'Garbage / Waste'), ('SECURITY', 'Security'), ('ELECTRICITY', 'Electricity'), ('OTHER', 'Other Utility')], help_text='Leave blank for non-utility ad-hocs.', max_length=16),
        ),
        migrations.AddField(
            model_name='historicaladhoccharge',
            name='utility_kind',
            field=models.CharField(blank=True, choices=[('WATER', 'Water'), ('GARBAGE', 'Garbage / Waste'), ('SECURITY', 'Security'), ('ELECTRICITY', 'Electricity'), ('OTHER', 'Other Utility')], help_text='Leave blank for non-utility ad-hocs.', max_length=16),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='utility_kind',
            field=models.CharField(blank=True, choices=[('WATER', 'Water'), ('GARBAGE', 'Garbage / Waste'), ('SECURITY', 'Security'), ('ELECTRICITY', 'Electricity'), ('OTHER', 'Other Utility')], help_text='For UTILITY lines only — which utility-income account to credit.', max_length=16),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='kind',
            field=models.CharField(choices=[('RENT', 'Rent'), ('AD_HOC', 'Ad-hoc'), ('PRORATA', 'Pro-rata rent'), ('UTILITY', 'Utility')], max_length=16),
        ),
    ]
