# Generated by Django 6.0.4 on 2026-04-24 14:40

import billing.models
import core.fields
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_drop_nssf_seed_utility_income'),
        ('billing', '0004_historicallandlordpayout_historicalsupplierpayment_and_more'),
        ('core', '0008_tenanthouse_uniq_active_tenancy_per_house'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalExpenseClaim',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AUTO_APPROVED', 'Auto-approved (trusted)')], default='PENDING', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('number', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('category', models.CharField(choices=[('MAINTENANCE_REPAIRS', 'Maintenance & Repairs'), ('UTILITIES', 'Utilities'), ('TRANSPORT', 'Transport'), ('OFFICE_SUPPLIES', 'Office supplies'), ('COMMS', 'Communications / Airtime'), ('LEGAL_PROFESSIONAL', 'Legal & professional'), ('OTHER', 'Other operating')], max_length=32)),
                ('description', models.CharField(help_text="What was this expense for? (e.g. 'Taxi to Buziga site — plumbing emergency')", max_length=255)),
                ('amount', core.fields.UGXField()),
                ('incurred_at', models.DateField(default=django.utils.timezone.localdate, help_text='Date the expense was actually incurred.')),
                ('receipt_photo', models.TextField(blank=True, help_text='Upload a photo of the receipt (optional but strongly recommended).', max_length=100, null=True)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('checker', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('claimant', models.ForeignKey(blank=True, db_constraint=False, help_text='Employee submitting the claim.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.employee')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('maker', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reimbursement_bank', models.ForeignKey(blank=True, db_constraint=False, help_text='Bank account / cash source used to reimburse the employee.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.bankaccount')),
                ('related_house', models.ForeignKey(blank=True, db_constraint=False, help_text='Optional — house this expense relates to (for cost allocation).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.house')),
                ('source_journal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.journalentry')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical expense claim',
                'verbose_name_plural': 'historical expense claims',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ExpenseClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AUTO_APPROVED', 'Auto-approved (trusted)')], default='PENDING', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('number', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('category', models.CharField(choices=[('MAINTENANCE_REPAIRS', 'Maintenance & Repairs'), ('UTILITIES', 'Utilities'), ('TRANSPORT', 'Transport'), ('OFFICE_SUPPLIES', 'Office supplies'), ('COMMS', 'Communications / Airtime'), ('LEGAL_PROFESSIONAL', 'Legal & professional'), ('OTHER', 'Other operating')], max_length=32)),
                ('description', models.CharField(help_text="What was this expense for? (e.g. 'Taxi to Buziga site — plumbing emergency')", max_length=255)),
                ('amount', core.fields.UGXField()),
                ('incurred_at', models.DateField(default=django.utils.timezone.localdate, help_text='Date the expense was actually incurred.')),
                ('receipt_photo', models.ImageField(blank=True, help_text='Upload a photo of the receipt (optional but strongly recommended).', null=True, upload_to=billing.models._expense_receipt_path)),
                ('notes', models.TextField(blank=True)),
                ('checker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('claimant', models.ForeignKey(help_text='Employee submitting the claim.', on_delete=django.db.models.deletion.PROTECT, related_name='expense_claims', to='core.employee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reimbursement_bank', models.ForeignKey(help_text='Bank account / cash source used to reimburse the employee.', on_delete=django.db.models.deletion.PROTECT, related_name='expense_claims', to='accounting.bankaccount')),
                ('related_house', models.ForeignKey(blank=True, help_text='Optional — house this expense relates to (for cost allocation).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_claims', to='core.house')),
                ('source_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_expense_claims', to='accounting.journalentry')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-incurred_at', '-id'],
                'indexes': [models.Index(fields=['claimant', 'incurred_at'], name='billing_exp_claiman_314743_idx'), models.Index(fields=['approval_status', 'incurred_at'], name='billing_exp_approva_7457b7_idx'), models.Index(fields=['category'], name='billing_exp_categor_53d3db_idx')],
            },
        ),
    ]
