# Generated by Django 6.0.4 on 2026-04-24 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_drop_nssf_seed_utility_income'),
        ('billing', '0005_historicalexpenseclaim_expenseclaim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseclaim',
            name='reimbursement_bank',
            field=models.ForeignKey(blank=True, help_text='Set by Finance when approving. Chooses the GL bank/cash account.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_claims', to='accounting.bankaccount'),
        ),
        migrations.AlterField(
            model_name='historicalexpenseclaim',
            name='reimbursement_bank',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Set by Finance when approving. Chooses the GL bank/cash account.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.bankaccount'),
        ),
    ]
