# Generated by Django 6.0.4 on 2026-04-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_expenseclaim_reimbursement_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhoccharge',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AUTO_APPROVED', 'Auto-approved (trusted)'), ('SENT_BACK', 'Sent back for revision')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AUTO_APPROVED', 'Auto-approved (trusted)'), ('SENT_BACK', 'Sent back for revision')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='exitsettlement',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AUTO_APPROVED', 'Auto-approved (trusted)'), ('SENT_BACK', 'Sent back for revision')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AUTO_APPROVED', 'Auto-approved (trusted)'), ('SENT_BACK', 'Sent back for revision')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='historicaladhoccharge',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AUTO_APPROVED', 'Auto-approved (trusted)'), ('SENT_BACK', 'Sent back for revision')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='historicalcreditnote',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AUTO_APPROVED', 'Auto-approved (trusted)'), ('SENT_BACK', 'Sent back for revision')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='historicalexitsettlement',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AUTO_APPROVED', 'Auto-approved (trusted)'), ('SENT_BACK', 'Sent back for revision')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='historicalexpenseclaim',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AUTO_APPROVED', 'Auto-approved (trusted)'), ('SENT_BACK', 'Sent back for revision')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='historicalinvoicevoid',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AUTO_APPROVED', 'Auto-approved (trusted)'), ('SENT_BACK', 'Sent back for revision')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='historicallandlordpayout',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AUTO_APPROVED', 'Auto-approved (trusted)'), ('SENT_BACK', 'Sent back for revision')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AUTO_APPROVED', 'Auto-approved (trusted)'), ('SENT_BACK', 'Sent back for revision')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='historicalrefund',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AUTO_APPROVED', 'Auto-approved (trusted)'), ('SENT_BACK', 'Sent back for revision')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='historicalsupplierpayment',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AUTO_APPROVED', 'Auto-approved (trusted)'), ('SENT_BACK', 'Sent back for revision')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='invoicevoid',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AUTO_APPROVED', 'Auto-approved (trusted)'), ('SENT_BACK', 'Sent back for revision')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='landlordpayout',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AUTO_APPROVED', 'Auto-approved (trusted)'), ('SENT_BACK', 'Sent back for revision')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='payment',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AUTO_APPROVED', 'Auto-approved (trusted)'), ('SENT_BACK', 'Sent back for revision')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='refund',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AUTO_APPROVED', 'Auto-approved (trusted)'), ('SENT_BACK', 'Sent back for revision')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AUTO_APPROVED', 'Auto-approved (trusted)'), ('SENT_BACK', 'Sent back for revision')], default='PENDING', max_length=16),
        ),
    ]
