# Generated by Django 6.0.4 on 2026-04-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_adhoccharge_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='purpose',
            field=models.CharField(choices=[('PERIODIC_RENT', 'Periodic rent'), ('INITIAL_DEPOSIT', 'Initial / move-in deposit'), ('SECURITY_DEPOSIT', 'Security deposit'), ('REPAIRS', 'Repairs / damages'), ('UTILITY', 'Utility (water / electricity / etc.)'), ('ARREARS', 'Arrears / catch-up'), ('OTHER', 'Other')], default='PERIODIC_RENT', help_text='What the tenant is paying for. Drives reporting + GL routing for non-rent receipts.', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('PERIODIC_RENT', 'Periodic rent'), ('INITIAL_DEPOSIT', 'Initial / move-in deposit'), ('SECURITY_DEPOSIT', 'Security deposit'), ('REPAIRS', 'Repairs / damages'), ('UTILITY', 'Utility (water / electricity / etc.)'), ('ARREARS', 'Arrears / catch-up'), ('OTHER', 'Other')], default='PERIODIC_RENT', help_text='What the tenant is paying for. Drives reporting + GL routing for non-rent receipts.', max_length=20),
        ),
    ]
