# Generated by Django 6.0.4 on 2026-05-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_historicalpayment_purpose_payment_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='receipt_image',
            field=models.TextField(blank=True, help_text='Optional photo of the physical receipt or proof of payment.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_image',
            field=models.ImageField(blank=True, help_text='Optional photo of the physical receipt or proof of payment.', null=True, upload_to='payment_receipts/%Y/%m/'),
        ),
    ]
