# Generated by Django 6.0.4 on 2026-04-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltenanthouse',
            name='invoice_generation_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicaltenanthouse',
            name='invoice_generation_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('STOPPED', 'Stopped')], default='ACTIVE', help_text='PAUSED skips generation but keeps accrual; STOPPED halts billing entirely.', max_length=16),
        ),
        migrations.AddField(
            model_name='tenanthouse',
            name='invoice_generation_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenanthouse',
            name='invoice_generation_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('STOPPED', 'Stopped')], default='ACTIVE', help_text='PAUSED skips generation but keeps accrual; STOPPED halts billing entirely.', max_length=16),
        ),
    ]
