# Generated by Django 6.0.4 on 2026-04-21 07:56

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historicaltenanthouse_invoice_generation_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='allowance_airtime',
            field=core.fields.UGXField(default=0, help_text='Monthly airtime allowance.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='allowance_housing',
            field=core.fields.UGXField(default=0, help_text='Monthly housing allowance.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='allowance_other',
            field=core.fields.UGXField(default=0, help_text='Other monthly allowances.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='allowance_transport',
            field=core.fields.UGXField(default=0, help_text='Monthly transport allowance.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='employee',
            name='base_salary',
            field=core.fields.UGXField(default=0, help_text='Gross monthly salary (UGX, whole shillings).'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('CONTRACT', 'Contract'), ('INTERN', 'Intern')], default='FULL_TIME', max_length=16),
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='employee',
            name='nssf_employee',
            field=core.fields.UGXField(default=0, help_text='NSSF employee contribution (5% of gross).'),
        ),
        migrations.AddField(
            model_name='employee',
            name='nssf_employer',
            field=core.fields.UGXField(default=0, help_text='NSSF employer contribution (10% of gross).'),
        ),
        migrations.AddField(
            model_name='employee',
            name='nssf_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='employee',
            name='other_deduction',
            field=core.fields.UGXField(default=0, help_text='Other monthly deductions.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='paye_monthly',
            field=core.fields.UGXField(default=0, help_text='PAYE withheld monthly (URA). Computed and snapshotted by payroll run.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tin',
            field=models.CharField(blank=True, help_text='URA Tax Identification Number.', max_length=32),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='allowance_airtime',
            field=core.fields.UGXField(default=0, help_text='Monthly airtime allowance.'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='allowance_housing',
            field=core.fields.UGXField(default=0, help_text='Monthly housing allowance.'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='allowance_other',
            field=core.fields.UGXField(default=0, help_text='Other monthly allowances.'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='allowance_transport',
            field=core.fields.UGXField(default=0, help_text='Monthly transport allowance.'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='base_salary',
            field=core.fields.UGXField(default=0, help_text='Gross monthly salary (UGX, whole shillings).'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='employment_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('CONTRACT', 'Contract'), ('INTERN', 'Intern')], default='FULL_TIME', max_length=16),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='job_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='nssf_employee',
            field=core.fields.UGXField(default=0, help_text='NSSF employee contribution (5% of gross).'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='nssf_employer',
            field=core.fields.UGXField(default=0, help_text='NSSF employer contribution (10% of gross).'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='nssf_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='other_deduction',
            field=core.fields.UGXField(default=0, help_text='Other monthly deductions.'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='paye_monthly',
            field=core.fields.UGXField(default=0, help_text='PAYE withheld monthly (URA). Computed and snapshotted by payroll run.'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='tin',
            field=models.CharField(blank=True, help_text='URA Tax Identification Number.', max_length=32),
        ),
        migrations.AddField(
            model_name='historicallandlord',
            name='preferred_statement_channel',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('BOTH', 'Both'), ('NONE', 'Do not auto-send')], default='EMAIL', help_text='How to auto-deliver the monthly landlord statement PDF.', max_length=16),
        ),
        migrations.AddField(
            model_name='historicallandlord',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp destination in E.164 if different from `phone`.', max_length=16),
        ),
        migrations.AddField(
            model_name='landlord',
            name='preferred_statement_channel',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('BOTH', 'Both'), ('NONE', 'Do not auto-send')], default='EMAIL', help_text='How to auto-deliver the monthly landlord statement PDF.', max_length=16),
        ),
        migrations.AddField(
            model_name='landlord',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp destination in E.164 if different from `phone`.', max_length=16),
        ),
    ]
