# Generated by Django 6.0.4 on 2026-04-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_employee_allowance_airtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='nssf_employee',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nssf_employer',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nssf_number',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='nssf_employee',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='nssf_employer',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='nssf_number',
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='employee',
            name='other_names',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='estate',
            name='electricity_billed_separately',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estate',
            name='other_bills_billed_separately',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estate',
            name='other_bills_description',
            field=models.CharField(blank=True, help_text="Free-text description of what 'other bills' covers at this level.", max_length=255),
        ),
        migrations.AddField(
            model_name='estate',
            name='security_billed_separately',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='first_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='last_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='other_names',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='historicalestate',
            name='electricity_billed_separately',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalestate',
            name='other_bills_billed_separately',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalestate',
            name='other_bills_description',
            field=models.CharField(blank=True, help_text="Free-text description of what 'other bills' covers at this level.", max_length=255),
        ),
        migrations.AddField(
            model_name='historicalestate',
            name='security_billed_separately',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalhouse',
            name='electricity_billed_separately',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalhouse',
            name='other_bills_billed_separately',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalhouse',
            name='other_bills_description',
            field=models.CharField(blank=True, help_text="Free-text description of what 'other bills' covers at this level.", max_length=255),
        ),
        migrations.AddField(
            model_name='historicalhouse',
            name='security_billed_separately',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicallandlord',
            name='first_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='historicallandlord',
            name='last_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='historicallandlord',
            name='other_names',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='historicaltenant',
            name='first_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='historicaltenant',
            name='last_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='historicaltenant',
            name='other_names',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='house',
            name='electricity_billed_separately',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='other_bills_billed_separately',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='other_bills_description',
            field=models.CharField(blank=True, help_text="Free-text description of what 'other bills' covers at this level.", max_length=255),
        ),
        migrations.AddField(
            model_name='house',
            name='security_billed_separately',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='first_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='landlord',
            name='last_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='landlord',
            name='other_names',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='tenant',
            name='first_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='tenant',
            name='last_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='tenant',
            name='other_names',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(help_text='Auto-composed from first/other/last on save. Do not edit directly.', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='full_name',
            field=models.CharField(help_text='Auto-composed from first/other/last on save. Do not edit directly.', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicallandlord',
            name='full_name',
            field=models.CharField(help_text='Auto-composed from first/other/last on save. Do not edit directly.', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicaltenant',
            name='full_name',
            field=models.CharField(help_text='Auto-composed from first/other/last on save. Do not edit directly.', max_length=200),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='full_name',
            field=models.CharField(help_text='Auto-composed from first/other/last on save. Do not edit directly.', max_length=200),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='full_name',
            field=models.CharField(help_text='Auto-composed from first/other/last on save. Do not edit directly.', max_length=200),
        ),
    ]
