# Generated by Django 6.0.4 on 2026-04-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_backfill_split_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(blank=True, help_text='Auto-composed from first/other/last on save. Do not edit directly.', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='full_name',
            field=models.CharField(blank=True, help_text='Auto-composed from first/other/last on save. Do not edit directly.', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicallandlord',
            name='full_name',
            field=models.CharField(blank=True, help_text='Auto-composed from first/other/last on save. Do not edit directly.', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicaltenant',
            name='full_name',
            field=models.CharField(blank=True, help_text='Auto-composed from first/other/last on save. Do not edit directly.', max_length=200),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='full_name',
            field=models.CharField(blank=True, help_text='Auto-composed from first/other/last on save. Do not edit directly.', max_length=200),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='full_name',
            field=models.CharField(blank=True, help_text='Auto-composed from first/other/last on save. Do not edit directly.', max_length=200),
        ),
    ]
