# Generated by Django 6.0.4 on 2026-04-24 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tenanthouse_uniq_active_tenancy_per_house'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tenanthouse',
            name='uniq_active_tenant_house',
        ),
        migrations.AddConstraint(
            model_name='tenanthouse',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('status', 'EXITED'), _negated=True)), fields=('tenant', 'house'), name='uniq_active_tenant_house'),
        ),
    ]
