# Generated by Django 6.0.4 on 2026-04-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_collectionsbonusbracket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive estates stop billing on every house under them.'),
        ),
        migrations.AddField(
            model_name='historicalestate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive estates stop billing on every house under them.'),
        ),
        migrations.AddField(
            model_name='historicalhouse',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive houses stop billing on the active tenancy.'),
        ),
        migrations.AddField(
            model_name='house',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive houses stop billing on the active tenancy.'),
        ),
    ]
