# Generated by Django 6.0.4 on 2026-04-29 04:53

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_estate_is_active_historicalestate_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Meili Property', max_length=120)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('tax_id', models.CharField(blank=True, max_length=64)),
                ('address_line_1', models.CharField(blank=True, max_length=200)),
                ('address_line_2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(default='Uganda', max_length=80)),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=core.models._company_logo_path)),
                ('receipt_footer', models.CharField(blank=True, help_text='Optional small print printed at the bottom of receipts.', max_length=255)),
            ],
            options={
                'verbose_name': 'Company profile',
                'verbose_name_plural': 'Company profile',
            },
        ),
    ]
