# Generated by Django 6.0.4 on 2026-04-22 14:06

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0005_drop_nssf_seed_utility_income'),
        ('billing', '0003_exitsettlement_historicalexitsettlement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human label for this integration (e.g. 'Stanbic Payments Webhook').", max_length=120)),
                ('key_prefix', models.CharField(db_index=True, max_length=16, unique=True)),
                ('hashed_key', models.CharField(max_length=128)),
                ('allowed_ips', models.TextField(blank=True, help_text='Optional comma-separated allowlist of source IPs. Empty = any.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(help_text='All payments authenticated with this key deposit to this bank account.', on_delete=django.db.models.deletion.PROTECT, related_name='api_keys', to='accounting.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalApiKey',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text="Human label for this integration (e.g. 'Stanbic Payments Webhook').", max_length=120)),
                ('key_prefix', models.CharField(db_index=True, max_length=16)),
                ('hashed_key', models.CharField(max_length=128)),
                ('allowed_ips', models.TextField(blank=True, help_text='Optional comma-separated allowlist of source IPs. Empty = any.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bank_account', models.ForeignKey(blank=True, db_constraint=False, help_text='All payments authenticated with this key deposit to this bank account.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical api key',
                'verbose_name_plural': 'historical api keys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=128)),
                ('source_name', models.CharField(blank=True, max_length=120)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('ACCEPTED', 'Accepted'), ('DUPLICATE', 'Duplicate'), ('UNMATCHED', 'Unmatched payer'), ('INVALID', 'Invalid payload'), ('ERROR', 'Error')], max_length=16)),
                ('response_code', models.PositiveSmallIntegerField(default=202)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('error_detail', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='api.apikey')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='billing.payment')),
            ],
            options={
                'ordering': ['-received_at', '-id'],
                'indexes': [models.Index(fields=['status', 'received_at'], name='api_webhook_status_72d256_idx')],
                'constraints': [models.UniqueConstraint(fields=('api_key', 'transaction_id'), name='uniq_api_key_transaction_id')],
            },
        ),
    ]
