# Generated by Django 6.0.4 on 2026-04-22 15:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN_SUCCESS', 'Login success'), ('LOGIN_FAILED', 'Login failed'), ('LOGOUT', 'Logout'), ('PASSWORD_RESET', 'Password reset'), ('PASSWORD_CHANGED', 'Password changed'), ('PERMISSION_DENIED', 'Permission denied'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('VOID', 'Void'), ('REFUND', 'Refund'), ('CREDIT_NOTE', 'Credit note'), ('PAYMENT', 'Payment'), ('EXPORT', 'Export'), ('API_CALL', 'API call'), ('OTHER', 'Other')], db_index=True, max_length=32)),
                ('target_type', models.CharField(blank=True, db_index=True, max_length=64)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('target_repr', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(blank=True, max_length=8)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['actor', '-timestamp'], name='accounts_au_actor_i_183206_idx'), models.Index(fields=['action', '-timestamp'], name='accounts_au_action_918219_idx'), models.Index(fields=['target_type', 'target_id'], name='accounts_au_target__0c7dca_idx')],
            },
        ),
    ]
