# Generated by Django 6.0.4 on 2026-04-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login success'), ('LOGIN_FAILED', 'Login failed'), ('LOGOUT', 'Logout'), ('PASSWORD_RESET', 'Password reset'), ('PASSWORD_CHANGED', 'Password changed'), ('PERMISSION_DENIED', 'Permission denied'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('VOID', 'Void'), ('REFUND', 'Refund'), ('CREDIT_NOTE', 'Credit note'), ('PAYMENT', 'Payment'), ('EXPORT', 'Export'), ('API_CALL', 'API call'), ('NOTIFICATION_SENT', 'Notification sent'), ('OTHER', 'Other')], db_index=True, max_length=32),
        ),
    ]
