# Generated by Django 6.0.4 on 2026-04-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_seed_chart_of_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljournalentry',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='reference',
            field=models.CharField(blank=True, max_length=48, null=True, unique=True),
        ),
    ]
