# Generated by Django 6.0.4 on 2026-05-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_historicalinternaltransfer_internaltransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentryline',
            name='receipt_image',
            field=models.ImageField(blank=True, help_text='Optional photo of the supporting receipt or document.', null=True, upload_to='journal_receipts/%Y/%m/'),
        ),
    ]
