# Generated by Django 6.0.4 on 2026-04-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnotificationdelivery',
            name='template',
            field=models.CharField(choices=[('PAYMENT_CONFIRMATION', 'Payment confirmation'), ('RECEIPT', 'Receipt'), ('OVERDUE_REMINDER', 'Overdue reminder'), ('STATEMENT', 'Landlord statement'), ('PASSWORD_RESET', 'Password reset'), ('ADMIN_PASSWORD', 'Admin-issued password'), ('GENERIC', 'Generic')], max_length=32),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='template',
            field=models.CharField(choices=[('PAYMENT_CONFIRMATION', 'Payment confirmation'), ('RECEIPT', 'Receipt'), ('OVERDUE_REMINDER', 'Overdue reminder'), ('STATEMENT', 'Landlord statement'), ('PASSWORD_RESET', 'Password reset'), ('ADMIN_PASSWORD', 'Admin-issued password'), ('GENERIC', 'Generic')], max_length=32),
        ),
    ]
